function LiftLogic(sm, config) {

var module = this

module.floors = {}

// Autogenerated with DRAKON Editor 1.30


function Buttons_CleanUp(self, floor) {
    
}

function Buttons_Created_default(self, floor) {
    // item 1664
    self.state = "Ready"
}

function Buttons_Created_init(self, floor) {
    // item 1815
    self.getBelow = getBelow
    self.getAbove = getAbove
    // item 1536
    initFloors(self)
    // item 1523
    self.state = "Ready"
}

function Buttons_Ready_callDash(self, floor) {
    // item 1631
    var row = getFloor(
    	self,
    	floor
    )
    // item 1632
    row.dashCalled = true
    // item 1634
    sm.sendMessage(
    	self.parent,
    	"go",
    	floor
    )
    // item 1526
    self.state = "Ready"
}

function Buttons_Ready_callDown(self, floor) {
    // item 1628
    var row = getFloor(
    	self,
    	floor
    )
    // item 1629
    row.downCalled = true
    // item 1634
    sm.sendMessage(
    	self.parent,
    	"go",
    	floor
    )
    // item 1526
    self.state = "Ready"
}

function Buttons_Ready_callUp(self, floor) {
    // item 1622
    var row = getFloor(
    	self,
    	floor
    )
    // item 1623
    row.upCalled = true
    // item 1634
    sm.sendMessage(
    	self.parent,
    	"go",
    	floor
    )
    // item 1526
    self.state = "Ready"
}

function Buttons_Ready_dim(self, floor) {
    // item 1636
    var row = getFloor(
    	self,
    	floor
    )
    // item 1637
    row.upCalled = false
    row.downCalled = false
    row.dashCalled = false
    // item 1795
    self.ctrl.dimFloor(floor)
    // item 1635
    self.state = "Ready"
}

function Cabin_CleanUp(self, msg) {
    
}

function Cabin_Created_default(self, msg) {
    // item 617
    self.state = "Created"
}

function Cabin_Created_init(self, msg) {
    // item 637
    self.current = msg
    // item 643
    var y = floorToHeight(msg)
    // item 635
    self.motor.init(y)
    // item 1806
    showFloor(self)
    // item 606
    self.state = "Still"
}

function Cabin_Moving_done(self, msg) {
    // item 634
    self.current = self.target
    // item 1807
    showFloor(self)
    // item 636
    sm.sendMessage(
    	self.parent,
    	"arrived",
    	self.target
    )
    // item 1727
    self.state = "Still"
}

function Cabin_Moving_move(self, msg) {
    // item 638
    setCabinTarget(self, msg)
    // item 632
    self.state = "Moving"
}

function Cabin_Moving_update(self, msg) {
    // item 645
    updateCabin(self, msg)
    // item 632
    self.state = "Moving"
}

function Cabin_Still_default(self, msg) {
    // item 1736
    self.state = "Still"
}

function Cabin_Still_move(self, msg) {
    // item 1733
    setCabinTarget(self, msg)
    // item 1734
    self.state = "Moving"
}

function Door_CleanUp(self, floor) {
    
}

function Door_Closed_default(self, floor) {
    // item 737
    self.state = "Closed"
}

function Door_Closed_open(self, floor) {
    // item 740
    self.motor.connect(floor)
    // item 718
    requestOpen(self)
    // item 671
    self.state = "Opening"
}

function Door_Closing_done(self, floor) {
    // item 724
    sm.sendMessage(
    	self.parent,
    	"closed",
    	null
    )
    // item 708
    self.state = "Closed"
}

function Door_Closing_open(self, floor) {
    // item 722
    requestOpen(self)
    // item 702
    self.state = "Opening"
}

function Door_Created_default(self, floor) {
    // item 727
    self.state = "Created"
}

function Door_Created_init(self, floor) {
    // item 1692
    var y = getCloseHeight()
    // item 1691
    self.motor.connect(floor)
    // item 719
    self.motor.init(y)
    // item 739
    self.state = "Closed"
}

function Door_Open_close(self, floor) {
    // item 721
    requestClose(self)
    // item 693
    self.state = "Closing"
}

function Door_Open_default(self, floor) {
    // item 699
    self.state = "Open"
}

function Door_Opening_close(self, floor) {
    // item 720
    requestClose(self)
    // item 684
    self.state = "Closing"
}

function Door_Opening_done(self, floor) {
    // item 723
    sm.sendMessage(
    	self.parent,
    	"opened",
    	null
    )
    // item 690
    self.state = "Open"
}

function LiftMain_CleanUp(self, floor) {
    
}

function LiftMain_Created_default(self, floor) {
    // item 860
    self.state = "Created"
}

function LiftMain_Created_init(self, floor) {
    // item 1748
    self.cabin.init(self.start)
    // item 889
    self.door.init(self.start)
    // item 1663
    self.sched.init()
    // item 1421
    self.state = "Ready"
}

function LiftMain_Ready_arrived(self, floor) {
    // item 1778
    openDoors(self)
    // item 1780
    self.state = "Ready"
}

function LiftMain_Ready_closed(self, floor) {
    // item 1774
    moveLift(self)
    // item 1780
    self.state = "Ready"
}

function LiftMain_Ready_go(self, floor) {
    // item 1792
    if ((self.cabin.state == "Still") && (floor == self.cabin.current)) {
        // item 1442
        openDoors(self)
    } else {
        // item 1445
        moveLift(self)
    }
    // item 1780
    self.state = "Ready"
}

function LiftMain_Ready_opened(self, floor) {
    // item 1704
    sm.sendMessageAfter(
    	self.door,
    	"close",
    	null,
    	config.OpenTimeout
    )
    // item 1780
    self.state = "Ready"
}

function Scheduler_CleanUp(self, floor) {
    
}

function Scheduler_Created_default(self, floor) {
    // item 1650
    self.state = "Created"
}

function Scheduler_Created_init(self, floor) {
    // item 1651
    self.buttons.init()
    // item 1766
    sm.forwardToChild(
    	self,
    	self.buttons,
    	"dim"
    )
    // item 1686
    sm.forwardToParent(
    	self,
    	"go"
    )
    // item 1648
    self.state = "Up"
}

function Scheduler_Down_chooseNext(self, floor) {
    // item 1684
    findBelow(self, floor)
    // item 1290
    if (self.target) {
        // item 1296
        self.state = "Down"
    } else {
        // item 1685
        findAbove(self, floor)
        // item 1295
        self.state = "Up"
    }
}

function Scheduler_Down_default(self, floor) {
    // item 1481
    self.state = "Down"
}

function Scheduler_Up_chooseNext(self, floor) {
    // item 1498
    findAbove(self, floor)
    // item 1487
    if (self.target) {
        // item 1492
        self.state = "Up"
    } else {
        // item 1683
        findBelow(self, floor)
        // item 1493
        self.state = "Down"
    }
}

function Scheduler_Up_default(self, floor) {
    // item 1497
    self.state = "Up"
}

function callDown(floor) {
    // item 1653
    module.buttons.callDown(floor)
}

function callUp(floor) {
    // item 1654
    module.buttons.callUp(floor)
}

function findAbove(self, floor) {
    // item 1675
    self.target = self.buttons.getAbove(
    	floor
    )
}

function findBelow(self, floor) {
    // item 1681
    self.target = self.buttons.getBelow(
    	floor
    )
}

function floorToHeight(floor) {
    // item 907
    return (floor - 1) * config.FloorHeight
}

function getAbove(floor) {
    // item 1559
    var i
    // item 15600001
    i = floor + 1;
    while (true) {
        // item 15600002
        if (i <= this.floorCount) {
            
        } else {
            // item 15740001
            i = this.floorCount;
            while (true) {
                // item 15740002
                if (i > floor) {
                    
                } else {
                    // item 1579
                    return null
                }
                // item 1584
                var row = getFloor(this, i)
                // item 1576
                if (row.downCalled) {
                    // item 1578
                    return i
                } else {
                    
                }
                // item 15740003
                i--;
            }
            break;
        }
        // item 1582
        var row = getFloor(this, i)
        // item 1562
        if ((row.upCalled) || (row.dashCalled)) {
            // item 1564
            return i
        } else {
            
        }
        // item 15600003
        i++;
    }
}

function getBelow(floor) {
    // item 1590
    var i
    // item 16130001
    i = floor;
    while (true) {
        // item 16130002
        if (i > 0) {
            
        } else {
            // item 16040001
            i = 1;
            while (true) {
                // item 16040002
                if (i < floor) {
                    
                } else {
                    // item 1609
                    return null
                }
                // item 1615
                var row = getFloor(this, i)
                // item 1592
                if (row.upCalled) {
                    // item 1608
                    return i
                } else {
                    
                }
                // item 16040003
                i++;
            }
            break;
        }
        // item 1614
        var row = getFloor(this, i)
        // item 1606
        if ((row.downCalled) || (row.dashCalled)) {
            // item 1594
            return i
        } else {
            
        }
        // item 16130003
        i--;
    }
}

function getCloseHeight() {
    // item 750
    return config.LiftHeight - 2
}

function getFloor(self, floor) {
    // item 1553
    return self.floors[floor]
}

function getOpenHeight() {
    // item 1690
    return 20
}

function go(floor) {
    // item 568
    module.buttons.callDash(floor)
}

function heightToFloor(height) {
    // item 913
    return Math.floor(height / config.FloorHeight) + 1
}

function init(builders, floorCount) {
    // item 596
    var tree = makeMachineTree(floorCount)
    var parent = {}
    // item 597
    module.root = sm.buildMachine(
    	builders,
    	parent,
    	tree
    )
    // item 598
    module.root.init()
    // item 1652
    module.buttons = sm.findSubobject(
    	module.root,
    	"sched/buttons"
    )
}

function initFloors(self) {
    // item 1546
    self.floors = {}
    // item 1544
    var i
    // item 15420001
    i = 1;
    while (true) {
        // item 15420002
        if (i <= self.floorCount) {
            
        } else {
            break;
        }
        // item 1545
        var row = {
        	dashCalled: false,
        	upCalled: false,
        	downCalled: false
        }
        // item 1547
        self.floors[i] = row
        // item 15420003
        i++;
    }
}

function makeBuilders() {
    // item 561
    var builders = {
    	CabinMovable: null,
    	Control: null,
    	ComplexDoor:null,
    	Motor: null,
    
    	Door: Door,
    	Cabin: Cabin,
    	LiftMain: LiftMain,
    	Scheduler: Scheduler,
    	Buttons: Buttons
    }
    // item 562
    return builders
}

function makeMachineTree(floorCount) {
    // item 1076
    return {
    	type: "LiftMain",
    	start: 1,
    	cabin: {
    		type: "Cabin",
    		motor: {
    			type: "Motor",
    			movable: {
    				type: "CabinMovable"
    			}
    		},
    		ctrl: { type: "Control" }
    	},
    	door: {
    		type: "Door",
    		motor: {
    			type: "Motor",
    			movable: {
    				type: "ComplexDoor"
    			}
    		}
    	},
    	sched: {
    		type: "Scheduler",
    		buttons: {
    			type: "Buttons",
    			floorCount: floorCount,
    			ctrl: { type: "Control" }
    		}
    	}
    }
}

function moveLift(self) {
    // item 1808
    if (self.door.state == "Closed") {
        // item 1746
        self.sched.chooseNext(
        	self.cabin.current
        )
        // item 1813
        var target = self.sched.target
        // item 1812
        if (target) {
            // item 1810
            self.cabin.move(target)
        } else {
            
        }
    } else {
        
    }
}

function openDoors(self) {
    // item 921
    var floor = self.cabin.current
    // item 920
    self.door.open(floor)
    // item 1662
    self.sched.dim(floor)
}

function requestClose(self) {
    // item 746
    self.motor.setTarget(getCloseHeight())
}

function requestOpen(self) {
    // item 756
    self.motor.setTarget(getOpenHeight())
}

function setCabinTarget(self, target) {
    // item 653
    self.target = target
    // item 652
    var height = floorToHeight(target)
    self.motor.setTarget(height)
}

function showFloor(self) {
    // item 1805
    self.ctrl.setCurrent(
    	self.current
    )
}

function updateCabin(self, pos) {
    // item 661
    var current = heightToFloor(pos)
    // item 662
    if (current == self.current) {
        
    } else {
        // item 660
        self.current = current
        // item 1804
        showFloor(self)
    }
}

function Cabin() {
  var _self = this;
  _self.type_name = "Cabin";
  _self.state = "Created";
  _self.done = function(msg) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Cabin_Created_default(_self, msg)
    }
    else if (_state_ == "Still") {
      Cabin_Still_default(_self, msg)
    }
    else if (_state_ == "Moving") {
      Cabin_Moving_done(_self, msg)
    }
  }
  _self.init = function(msg) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Cabin_Created_init(_self, msg)
    }
    else if (_state_ == "Still") {
      Cabin_Still_default(_self, msg)
    }
  }
  _self.move = function(msg) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Cabin_Created_default(_self, msg)
    }
    else if (_state_ == "Still") {
      Cabin_Still_move(_self, msg)
    }
    else if (_state_ == "Moving") {
      Cabin_Moving_move(_self, msg)
    }
  }
  _self.update = function(msg) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Cabin_Created_default(_self, msg)
    }
    else if (_state_ == "Still") {
      Cabin_Still_default(_self, msg)
    }
    else if (_state_ == "Moving") {
      Cabin_Moving_update(_self, msg)
    }
  }
}

function Door() {
  var _self = this;
  _self.type_name = "Door";
  _self.state = "Created";
  _self.close = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Door_Created_default(_self, floor)
    }
    else if (_state_ == "Closed") {
      Door_Closed_default(_self, floor)
    }
    else if (_state_ == "Opening") {
      Door_Opening_close(_self, floor)
    }
    else if (_state_ == "Open") {
      Door_Open_close(_self, floor)
    }
  }
  _self.done = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Door_Created_default(_self, floor)
    }
    else if (_state_ == "Closed") {
      Door_Closed_default(_self, floor)
    }
    else if (_state_ == "Opening") {
      Door_Opening_done(_self, floor)
    }
    else if (_state_ == "Open") {
      Door_Open_default(_self, floor)
    }
    else if (_state_ == "Closing") {
      Door_Closing_done(_self, floor)
    }
  }
  _self.init = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Door_Created_init(_self, floor)
    }
    else if (_state_ == "Closed") {
      Door_Closed_default(_self, floor)
    }
    else if (_state_ == "Open") {
      Door_Open_default(_self, floor)
    }
  }
  _self.open = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Door_Created_default(_self, floor)
    }
    else if (_state_ == "Closed") {
      Door_Closed_open(_self, floor)
    }
    else if (_state_ == "Open") {
      Door_Open_default(_self, floor)
    }
    else if (_state_ == "Closing") {
      Door_Closing_open(_self, floor)
    }
  }
}

function LiftMain() {
  var _self = this;
  _self.type_name = "LiftMain";
  _self.state = "Created";
  _self.arrived = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      LiftMain_Created_default(_self, floor)
    }
    else if (_state_ == "Ready") {
      LiftMain_Ready_arrived(_self, floor)
    }
  }
  _self.closed = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      LiftMain_Created_default(_self, floor)
    }
    else if (_state_ == "Ready") {
      LiftMain_Ready_closed(_self, floor)
    }
  }
  _self.go = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      LiftMain_Created_default(_self, floor)
    }
    else if (_state_ == "Ready") {
      LiftMain_Ready_go(_self, floor)
    }
  }
  _self.init = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      LiftMain_Created_init(_self, floor)
    }
  }
  _self.opened = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      LiftMain_Created_default(_self, floor)
    }
    else if (_state_ == "Ready") {
      LiftMain_Ready_opened(_self, floor)
    }
  }
}

function Scheduler() {
  var _self = this;
  _self.type_name = "Scheduler";
  _self.state = "Created";
  _self.chooseNext = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Scheduler_Created_default(_self, floor)
    }
    else if (_state_ == "Up") {
      Scheduler_Up_chooseNext(_self, floor)
    }
    else if (_state_ == "Down") {
      Scheduler_Down_chooseNext(_self, floor)
    }
  }
  _self.init = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Scheduler_Created_init(_self, floor)
    }
    else if (_state_ == "Up") {
      Scheduler_Up_default(_self, floor)
    }
    else if (_state_ == "Down") {
      Scheduler_Down_default(_self, floor)
    }
  }
}

function Buttons() {
  var _self = this;
  _self.type_name = "Buttons";
  _self.state = "Created";
  _self.callDash = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Buttons_Created_default(_self, floor)
    }
    else if (_state_ == "Ready") {
      Buttons_Ready_callDash(_self, floor)
    }
  }
  _self.callDown = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Buttons_Created_default(_self, floor)
    }
    else if (_state_ == "Ready") {
      Buttons_Ready_callDown(_self, floor)
    }
  }
  _self.callUp = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Buttons_Created_default(_self, floor)
    }
    else if (_state_ == "Ready") {
      Buttons_Ready_callUp(_self, floor)
    }
  }
  _self.dim = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Buttons_Created_default(_self, floor)
    }
    else if (_state_ == "Ready") {
      Buttons_Ready_dim(_self, floor)
    }
  }
  _self.init = function(floor) {
    var _state_ = _self.state
    if (_state_ == "Created") {
      Buttons_Created_init(_self, floor)
    }
  }
}


module.makeBuilders = makeBuilders
module.go = go
module.callDown = callDown
module.callUp = callUp
module.init = init
module.makeMachineTree = makeMachineTree

}
